server {
    listen 80;
    server_name _;
    # Kalau mau force HTTPS dari HTTP, uncomment baris di bawah:
    # return 301 https://$host$request_uri;

    # Hapus blok location /api/v1/uploads/ agar di handle oleh Backend Go langsung

    # Proxy to Backend API
    location /api/ {
        proxy_pass http://kartcis-backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 10M;
    }

    # Proxy to Frontend
    location / {
        proxy_pass http://kartcis-frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name kartcis.id www.kartcis.id;

    # Sesuaikan dengan nama folder di VPS jika bukan kartcis.id
    ssl_certificate /etc/letsencrypt/live/kartcis.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kartcis.id/privkey.pem;
    # Hapus blok location /api/v1/uploads/ agar di handle oleh Backend Go langsung

    # Proxy to Backend API
    location /api/ {
        proxy_pass http://kartcis-backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        client_max_body_size 10M;
    }

    # Proxy to Frontend
    location / {
        proxy_pass http://kartcis-frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
